Fixes some issues in the FortCL implementation
stfc/FortCL pull request #13
Opened 2020-06-25 15:30 UTC by sergisiso

Fix #11 by reading the file in binary format and passing it as it is to the OpenCL runtime (avoids dealing with encoding)
Fix #12 by transforming OpenCL binded functions to function interfaces.

This implementation was branched from PR #10 branch, so that PR needs to go first.

2020-07-01 12:33 UTC, sergisiso commented
@arporter This is ready for review now. This cleans up a big part of PSycloneBench makefile compiler warnings and fixes some encoding problems that appear from time to time when using the NemoLite2D FortCL and PSyclone generated OpenCL implementations.

2020-07-02 15:03 UTC, arporter requested changes
Looks good and a big improvement over what we had originally.
I can build the lib on my desktop (although I can't run the examples because I no longer have a working OpenCL installation).
Only issue of any significance is to improve the verbosity of an error message. Once that's done I will merge.

2020-07-02 15:03 UTC, arporter commented on src/clfortran.f90
> +    contains
I don't think you need this line (but I may be wrong)?

2020-07-02 15:03 UTC, arporter commented on src/ocl_utils_mod.f90
> +    if (iallocerr.ne.0) stop 'Error allocating buffer'
Please extend a little to say which kernel/file and how many bytes we were attempting to allocate.

2020-07-02 15:03 UTC, arporter commented on src/ocl_utils_mod.f90
> +    inquire(iunit, SIZE=binary_size)
That's a lot nicer than the code I had!

2020-07-02 15:03 UTC, arporter commented on src/clfortran.f90
> +    interface
I think this lack of the use of `interface` must be the reason I had terrible trouble originally when I included clfortran.o in the objects being compiled - I got a binary but it did nothing.

2020-07-03 10:30 UTC, sergisiso commented on src/clfortran.f90
> +    contains
Yeah, it works without it.

2020-07-03 10:31 UTC, sergisiso commented on src/ocl_utils_mod.f90
> +    if (iallocerr.ne.0) stop 'Error allocating buffer'
Improved error message

2020-07-03 10:34 UTC, sergisiso commented
@arporter I made the suggested changes, ready for next review.

2020-07-03 13:02 UTC, arporter approved these changes

2020-07-03 13:02 UTC, merged